EXECUTE [dbo].[IML_APP_INSERT]
        @p_AppId OUTPUT,
        @p_AppTypeId,
        @p_AppReasonId,
        @p_AppReasonIds,
        @p_SgdAppNum,
        @p_SgdAppDate,
        @p_RegAppNum,
        @p_RegAppDate,
        @p_PersonId,
        @p_IsFree,			
	    @p_Notes,				
	    @p_BranchCount,					
	    @p_IsActsReceived,			
	    @p_LicDocId,						
	    @p_SideEdrpou,		
	    @p_OrgformId,		
	    @p_SideName	,		
	    @p_RegionId	,		
	    @p_SideAddress,		
	    @p_SideIndex	,	
	    @p_SideDirectorPib,	
	    @p_SideContacts		,
	    @p_BankAccount		,
	    @p_Email			,
	    @p_IsImportReady,
	    @p_IsImportInbulk,
	    @p_ImportOther		,
	    @p_OpfgTypeId		,
	    @p_OwnershipTypeId	,
	    @p_KvedId			,
	    @p_SpoduId		,
	    @p_CreatorName	,	
	    @p_CreateDate		

    