           EXECUTE [dbo].[PRL_APP_BRANCH_INSERT]
            @p_BranchAppId OUTPUT
           , @p_BranchLicId
           , @p_AppId
           , @p_BranchNumber
           , @p_BranchName
           , @p_IsAddressMatches
           , @p_RegionId
           , @p_ResidenceTypeId
           , @p_BranchAddress
           , @p_OperationForm
           , @p_BranchAddressIdx
           , @p_Phone
           , @p_SpecialConditions
           , @p_IsSaveConditions